Repository CertifaiAI/Classifai_FrontEnd, pull requests merged in 2021-07, with the labels that each got.

#194 Fix shortcut key configuration for MacOS
  src/assets/i18n/image-labelling-cn.json
  src/assets/i18n/image-labelling-en.json
  src/assets/i18n/image-labelling-ms.json
  src/components/image-labelling/image-labelling-object-detection/bounding-box-canvas.service.ts
  src/components/image-labelling/image-labelling-object-detection/image-labelling-object-detection.component.ts
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.ts
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
  src/shared/services/shortcut-key.service.ts
Labels: uidesign

#193 Refactor create new project and import project API call
  src/layouts/data-set-layout/data-set-layout-api.service.ts
  src/layouts/data-set-layout/data-set-layout.component.ts
  src/shared/types/message/message.model.ts
Labels: enhancement

#196 🐛 Sorting Project based on AM/PM
  .gitignore
  src/components/data-set/data-set-card/data-set-card.component.html
  src/layouts/data-set-layout/data-set-layout.component.ts
  src/layouts/data-set-layout/data-set-layout.model.ts
Labels: bug

#197 Show the project list based on the chosen category at side menu in Dataset Management page.
  src/components/data-set/data-set-header/data-set-header.component.html
  src/components/data-set/data-set-header/data-set-header.component.ts
  src/components/data-set/data-set-side-menu/data-set-side-menu.component.html
  src/components/data-set/data-set-side-menu/data-set-side-menu.component.scss
  src/components/data-set/data-set-side-menu/data-set-side-menu.component.ts
  src/layouts/data-set-layout/data-set-layout.component.html
  src/layouts/data-set-layout/data-set-layout.component.ts
Labels: enhancement

#199 Code Refactoring 2
  src/assets/i18n/data-set-page-cn.json
  src/assets/i18n/data-set-page-en.json
  src/assets/i18n/data-set-page-ms.json
  src/components/data-set/data-set-card/data-set-card.component.html
  src/components/data-set/data-set-card/data-set-card.component.scss
  src/components/data-set/data-set-card/data-set-card.component.ts
  src/components/data-set/data-set-header/data-set-header.component.html
  src/components/data-set/data-set-header/data-set-header.component.scss
  src/components/data-set/data-set-side-menu/data-set-side-menu.component.html
  src/components/data-set/data-set-side-menu/data-set-side-menu.component.scss
  src/components/home/home-card/home-card.component.scss
  src/components/home/home-header/home-header.component.html
  src/components/home/home-header/home-header.component.scss
  src/components/image-labelling/image-labelling-footer/image-labelling-footer.component.html
  src/components/image-labelling/image-labelling-footer/image-labelling-footer.component.scss
  src/components/image-labelling/image-labelling-info/image-labelling-info.component.html
  src/components/image-labelling/image-labelling-info/image-labelling-info.component.scss
  src/components/image-labelling/image-labelling-object-detection/image-labelling-object-detection.component.html
  src/components/image-labelling/image-labelling-object-detection/image-labelling-object-detection.component.scss
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.html
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.scss
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.html
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.scss
  src/layouts/data-set-layout/data-set-layout.component.html
  src/shared/components/empty-container/empty-container.component.html
  src/shared/components/empty-container/empty-container.component.scss
  src/shared/components/empty-container/empty-container.component.ts
  src/shared/components/empty-container/empty-container.module.ts
  src/shared/components/modal/modal.component.html
  src/shared/components/modal/modal.component.scss
  src/shared/components/page-header/page-header.component.html
  src/shared/components/page-header/page-header.component.scss
  src/shared/components/spinner/spinner.component.html
  src/shared/components/spinner/spinner.component.scss
  src/shared/shared.module.ts
Labels: chore
