Repository CertifaiAI/Classifai_FrontEnd, pull requests merged in 2021-06, with the labels that each got.

#163 Improve UI in Classifai Homepage.
  src/assets/landing-page/Classifai_Community_Logo.png
  src/components/home/home-card/home-card.component.html
  src/components/home/home-card/home-card.component.scss
  src/components/home/home-footer/home-footer.component.html
  src/components/home/home-footer/home-footer.component.scss
  src/components/home/home-footer/home-footer.component.ts
  src/components/home/home-header/home-header.component.html
  src/components/home/home-header/home-header.component.scss
  src/components/home/home-header/home-header.component.ts
  src/layouts/home-layout/home-layout.component.html
  src/layouts/home-layout/home-layout.module.ts
Labels: uidesign

#165 Fix bugs in segmentation, show label list after drawing a polygon
  src/components/image-labelling/image-labelling-object-detection/bounding-box-canvas.service.ts
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.ts
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.html
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.scss
  src/components/image-labelling/image-labelling-segmentation/image-labelling-segmentation.component.ts
  src/components/image-labelling/image-labelling-segmentation/segmentation-canvas.service.ts
  src/layouts/image-labelling-layout/image-labelling-layout.component.html
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
  src/shared/services/undo-redo.service.ts
Labels: bug

#175 Update copy workflow to add merged PR's URL in commit message
  .github/workflows/copy.yml
Labels: ci/cd, enhancement

#179 Create code test workflow for Node.js
  .github/workflows/build.yml
  README.md
Labels: ci/cd, documentation

#186 Updated copy workflow to add auto code compiler
  .github/workflows/copy.yml
Labels: ci/cd

#185 Fix Annotation Details Negative Value when Exporting Project
  dist/classifai/1-es2015.9bd38b98fb13070aa286.js
  dist/classifai/1-es5.9bd38b98fb13070aa286.js
  dist/classifai/2-es2015.d90c06cb6ae046d13947.js
  dist/classifai/2-es5.d90c06cb6ae046d13947.js
  dist/classifai/7-es2015.f88b4e1b1a1da5519bb9.js
  dist/classifai/7-es5.f88b4e1b1a1da5519bb9.js
  dist/classifai/index.html
  dist/classifai/main-es2015.81aa37678a16b20e8ad5.js
  dist/classifai/main-es5.81aa37678a16b20e8ad5.js
  dist/classifai/runtime-es2015.277735cd188361365d5d.js
  dist/classifai/runtime-es5.277735cd188361365d5d.js
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
Labels: bug

#182 Show Warning if No Label is Selected during Export Project
  dist/classifai/2-es2015.5c49918f4ebbc9c9b95b.js
  dist/classifai/2-es5.5c49918f4ebbc9c9b95b.js
  dist/classifai/assets/i18n/image-labelling-cn.json
  dist/classifai/assets/i18n/image-labelling-en.json
  dist/classifai/assets/i18n/image-labelling-ms.json
  dist/classifai/index.html
  dist/classifai/runtime-es2015.54efcb2bfeab16f86b86.js
  dist/classifai/runtime-es5.54efcb2bfeab16f86b86.js
  src/assets/i18n/image-labelling-cn.json
  src/assets/i18n/image-labelling-en.json
  src/assets/i18n/image-labelling-ms.json
  src/layouts/image-labelling-layout/image-labelling-layout.component.html
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
  src/shared/services/export-save-format.service.ts
Labels: bug

#192 Add validations for renaming image
  src/assets/i18n/image-labelling-cn.json
  src/assets/i18n/image-labelling-en.json
  src/assets/i18n/image-labelling-ms.json
  src/layouts/image-labelling-layout/image-labelling-layout.component.html
  src/layouts/image-labelling-layout/image-labelling-layout.component.scss
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
Labels: enhancement

#188 Add Sorting Function for Projects in Dataset Layout Page
  src/assets/i18n/data-set-page-cn.json
  src/assets/i18n/data-set-page-en.json
  src/assets/i18n/data-set-page-ms.json
  src/components/data-set/data-set-card/data-set-card.component.html
  src/components/data-set/data-set-header/data-set-header.component.html
  src/components/data-set/data-set-header/data-set-header.component.scss
  src/components/data-set/data-set-header/data-set-header.component.ts
  src/layouts/data-set-layout/data-set-layout.component.html
  src/layouts/data-set-layout/data-set-layout.component.ts
  src/layouts/data-set-layout/data-set-layout.model.ts
Labels: enhancement

#191 Delete Image
  src/assets/i18n/image-labelling-cn.json
  src/assets/i18n/image-labelling-en.json
  src/assets/i18n/image-labelling-ms.json
  src/components/image-labelling/image-labelling-api.service.ts
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.html
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.scss
  src/components/image-labelling/image-labelling-project/image-labelling-project.component.ts
  src/components/modal/modal.component.ts
  src/components/modal/modal.service.ts
  src/layouts/image-labelling-layout/image-labelling-layout.component.html
  src/layouts/image-labelling-layout/image-labelling-layout.component.scss
  src/layouts/image-labelling-layout/image-labelling-layout.component.ts
  src/shared/types/message/message.model.ts
Labels: enhancement
